- type: department
  id: Acorp
  name: department-acorp
  description: department-acorp-description
  color: "#e8e8e8"
  weight: 26 # accounted for in jobs
  roles:
  - Acorp–°ommandant
  - AcorpDirector
  - AcorpSecurity
  - AcorpScience
  - AcorpEngineer
  - AcorpMedical
  - AcorpService
  - AcorpAssistant

- type: department
  id: Separatists
  name: department-separatists
  description: department-separatists-description
  color: "#5A3D30"
  weight: -20 # accounted for in jobs
  roles:
  - SeparatistsCommander
  - SeparatistsPrivateSlave
  - SeparatistsOperative
  - SeparatistsWarden
  - SeparatistsRecruit
  - SeparatistsSlave

- type: department
  id: Navy
  name: department-navy
  description: department-navy-description
  color: "#9589d6"
  weight: 2
  roles:
  - NavyKomandor
  - NavyCaptain
  - NavyOfficer
  - NavyBrigmedic
  - NavyCadet

- type: department
  id: MedicalPhoenix
  name: department-medical_phoenix
  description: department-medical_phoenix-description
  color: "#52B4E9"
  weight: -1
  roles:
  - DirectorOfCare
  - PhoenixAgent
  - PhoenixMedic

