- type: job
  id: NavyKomandor
  name: job-name-navy-komandor
  description: job-description-navy-komandor
  playTimeTracker: JobNavyKomandor
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 172800 # 48 hours Radiant_Sector
    - !type:DepartmentTimeRequirement
      department: Navy
      time: 86400 # 24 hours
    - !type:RoleTimeRequirement
      role: JobNavyCaptain
      time: 21600 # 6 hours
  startingGear: NavyKomandorGear
  icon: "JobIconNavyKomandor" 
  supervisors: job-supervisors-navy-cc
  weight: 190
  displayWeight: 75
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplantNavy ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: NavyKomandorGear
  equipment:
    pocket1: NFWeaponPistolUniversalNfsd
  storage:
    back:
    - NfsdTechFabFlatpack
    - Multitool
    - DoorRemoteNfsd
    - BaseNavyUplinkRadioKomandor
    - RubberStampSheriff
    - NavyToken2
    - NFPouchNavy