- type: job
  id: NavyCaptain
  name: job-name-navy-captain
  description: job-description-navy-captain
  playTimeTracker: JobNavyCaptain
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 57600 # 16 hours Radiant_Sector
    - !type:DepartmentTimeRequirement
      department: Navy
      time: 18000 # 5 hours
    - !type:RoleTimeRequirement
      role: JobNavyOfficer
      time: 10800 # 3 hours
  startingGear: NavyCaptainGear
  icon: "JobIconNavyCaptain" 
  supervisors: job-supervisors-navy-komandor
  weight: 154
  displayWeight: 61
  access:
  - Armory
  accessGroups:
  - NavyOfficerAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplantNavy ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: NavyCaptainGear
  equipment:
    pocket1: NFWeaponPistolUniversalNfsdLessLethal
  storage:
    back:
    - Flash
    - NFMagazineHighCapacityPistol35Overpressure
    - BaseNavyUplinkRadioCaptain
    - RubberStampBailiff
    - NavyToken2
    - NFPouchNavy