- type: job
  id: NavyOfficer
  name: job-name-navy-officer
  description: job-description-navy-officer
  playTimeTracker: JobNavyOfficer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 28800 # 8 hours Radiant_Sector
    - !type:DepartmentTimeRequirement
      department: Navy
      time: 7200 # 2 hours Radiant_Sector
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 180000 # 50 hours Radiant_Sector
  startingGear: NavyOfficerGear
  icon: "JobIconNavyOfficer" 
  supervisors: job-supervisors-navy-captain
  weight: 139
  displayWeight: 41
  accessGroups:
  - NavyOfficerAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplantNavy ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: NavyOfficerGear
  equipment:
    pocket1: NFWeaponPistolUniversalNfsd
  storage:
    back:
    - Flash
    - NFMagazineHighCapacityPistol35Overpressure
    - FrontierUplinkCoin10
    - NavyToken1
    - NFPouchNavy
